---
behaviors:
  movement:
    action_profile: cross
    state_profile:
      - this.d_rx
      - this.d_ry
      - this.d_rz
    reward_profile:
      - type: delta_position
      - type: sum
        args:
          variables:
            - this.d_rx
            - this.d_ry
            - this.d_rz
          absolute: True
    curiosity_weight: 0.0
    q_model_type: tables
    n_state_tiles: 3
    n_state_tilings: 1
    time_step: 1.0
    learning_rate: 0.5
    #learning_rate: 0.2
    epsilon: 0.05
    gamma: 0.5
    n_hidden_forward: 3
    max_speed: 0.8
    max_steer: 0.5
robots:
  robot1: movement
  robot2: movement
  robot3: movement
#  robot2: immobilisme2
